---
- name: ensure dockerfile directories exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache"
    - "{{ ansible_env.PWD }}/.ansible_cache/docker"

- name: synchronize role to remote cache for Dockerfile build
  synchronize:
    src: ../
    dest: "{{ ansible_env.PWD }}/.ansible_cache/docker/nova-compute"
    archive: no
    checksum: yes
    recursive: yes

- name: ensure docker image configuration directory exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache/docker/nova-compute/provisioning/group_vars"

- name: update configuration used to build docker image from template
  template:
    src: ansible_cache/docker/nova-compute/provisioning/group_vars/all.yml
    owner: "{{ ansible_ssh_user }}"
    dest: "{{ ansible_env.PWD }}/.ansible_cache/docker/nova-compute/provisioning/group_vars/all.yml"

- name: ensure nova docker image has been built
  docker_image:
    name: "{{ nova_compute_docker_username }}/{{ nova_compute_docker_imagename }}"
    path: "{{ ansible_env.PWD }}/.ansible_cache/docker/nova-compute"
    state: present

- name: ensure nova data container exists
  docker:
    image: "{{ nova_compute_docker_username }}/{{ nova_compute_docker_imagename }}"
    name: "{{ nova_compute_docker_containername }}_data"
    command: >
      ansible-playbook 
        -i inventories/local.ini provisioning/configure.yml -e '{ 
          "openstack_log_verbose" : "{{ openstack_log_verbose }}",
          "openstack_log_debug" : "{{ openstack_log_debug }}",
          "openstack_rabbitmq_host" : "{{ openstack_rabbitmq_host }}",
          "openstack_rabbitmq_port" : "{{ openstack_rabbitmq_port }}",
          "openstack_rabbitmq_nova_password" :
            "{{ openstack_rabbitmq_nova_password }}",
          "openstack_image_endpoint_host" : 
            "{{ openstack_image_endpoint_host }}",
          "openstack_compute_endpoint_host" : 
            "{{ openstack_compute_endpoint_host }}",
          "openstack_compute_node_ip" : "{{ openstack_compute_node_ip }}",
          "openstack_network_internal_url" : 
            "{{ openstack_network_internal_url }}",
          "openstack_identity_neutron_password" : 
            "{{ openstack_identity_neutron_password }}",
           "openstack_identity_internal_url" : 
            "{{ openstack_identity_internal_url }}",
          "openstack_mysql_host" : "{{ openstack_mysql_host }}",
          "openstack_mysql_port" : "{{ openstack_mysql_port }}",
          "openstack_mysql_nova_password" :
            "{{ openstack_mysql_nova_password }}",
          "openstack_identity_endpoint_host" : 
            "{{ openstack_identity_endpoint_host }}",
         "openstack_identity_nova_password" : 
            "{{ openstack_identity_nova_password }}",
          "openstack_compute_virt_type" : "{{ openstack_compute_virt_type }}" }'
    detach: no
    state: present

- name: wait until configuration is completed
  command: docker wait "{{ nova_compute_docker_containername }}_data"
  register: docker_wait
  changed_when: false

- name: collect configuration log
  command: docker logs "{{ nova_compute_docker_containername }}_data"
  register: configuration_log
  changed_when: false

- name: display configuration log
  debug:
    msg: "{{ configuration_log.stdout_lines }}"

- name: fail on configuration failure
  assert:
    that: docker_wait.stdout == "0"

- name: ensure nova service is running
  docker:
    image: "{{ nova_compute_docker_username }}/{{ nova_compute_docker_imagename }}"
    name: "{{ nova_compute_docker_containername }}_server"
    volumes_from: "{{ nova_compute_docker_containername }}_data"
    privileged: yes
    net: host
    detach: yes
    state: running

