---
- name: ensure nova compute packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nova-compute
    - neutron-common
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: ensure that pip is installed
  shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
         creates=/usr/local/bin/pip

- name: ensure nova user is a member of the docker group
  user:
    name: nova
    groups: docker
    append: yes
    state: present
  register: nova_user_mod

- name: restart nova-compute if necessary
  service:
    name: nova-compute
    state: restarted
  when: nova_user_mod|changed

#- name: ensure nova-compute-docker is installed
#  pip:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - oslo.rootwrap
#    - git+https://github.com/stackforge/nova-docker#egg=novadocker

- name: update rootwrap docker.filters from template
  template:
    owner: root
    group: root
    mode: 0755
    src: etc/nova/rootwrap.d/docker.filters
    dest: /etc/nova/rootwrap.d/docker.filters
    
- name: ensure nova compute is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - nova-compute
    - openvswitch-switch

- name: ensure nova compute is properly shut down for dockerized deployments
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - nova-compute
    - openvswitch-switch
  when: nova_compute_dockerize_context is defined

- name: ensure supervisor is installed for dockerized deployments 
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - supervisor
  when: nova_compute_dockerize_context is defined

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644
  when: nova_compute_dockerize_context is defined
