---
- name: ensure that software-properties-common is installed if needed
  apt:
    pkg: software-properties-common
    state: latest
    update_cache: yes
    cache_valid_time: 600
  when: ansible_distribution_release == "precise"

- name: ensure that ubuntu cloud archive is available if needed
  command: apt-add-repository cloud-archive:icehouse
  when: ansible_distribution_release == "precise"

- name: ensure nova compute packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nova-compute-lxc
    - neutron-common
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: ensure that pip is installed
  shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
         creates=/usr/local/bin/pip

- name: ensure nova-compute-docker is installed using pip
  command: pip install {{ openstack_compute_nova_docker_package }}
  args:
    creates: /usr/local/lib/python2.7/dist-packages/novadocker

- name: update rootwrap docker.filters from template
  template:
    owner: root
    group: root
    mode: 0755
    src: etc/nova/rootwrap.d/docker.filters
    dest: /etc/nova/rootwrap.d/docker.filters
    
- name: ensure nova compute is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - nova-compute
    - openvswitch-switch
