---
- name: ensure nova compute packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - "{{ nova_compute_package }}"

- name: ensure that directories used by nova exist and have correct permissions
  file:
    path: "{{ item }}"
    owner: nova
    group: nova
    mode: 0700
    state: directory
  with_items:
    - /var/run/nova
    - /var/lock/nova

- name: ensure supervisor is installed for dockerized deployments 
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - supervisor

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644

- name: ensure nova compute is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - nova-compute

- name: ensure nova compute is properly shut down for dockerized deployments
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - nova-compute
  when: nova_compute_dockerize_context is defined
