---
- include: docker.yml
  when: nova_compute_dockerized_deployment

- include: install.yml
  when: not nova_compute_dockerized_deployment 

- include: offline_configuration.yml
  when: not nova_compute_dockerized_deployment 
