---
- include: docker.yml
  when: nova_compute_dockerized_deployment

- include: install-ubuntu-trusty.yml
  when: not nova_compute_dockerized_deployment and
        ansible_distribution == "Ubuntu" and
        ansible_distribution_release == "trusty"

- include: install-centos6.yml
  when: not nova_compute_dockerized_deployment and
        ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "6"

- include: configure.yml
  when: not nova_compute_dockerized_deployment 

#- service:
#    name: "{{ item }}"
#    state: restarted 
#  with_items:
#    - neutron-server
#    - neutron-plugin-openvswitch-agent
#    - neutron-l3-agent
#    - neutron-dhcp-agent
#    - neutron-metadata-agent
#    - nova-compute 
#    - nova-api
#    - nova-cert
#    - nova-consoleauth
#    - nova-scheduler
#    - nova-conductor
#    - nova-novncproxy
 
